### ISSUE TITLE
gfw_list china_ip

### ISSUE THREAD

**Issue by lindong629** [chenanmo/ikuai-tools#1]
请问gfw_list和china_ip的格式应该是怎么写的。

**Comment by chenanmo** [comment]
一行一个域名或者一行一个IP(IP段),该文件可以从OpenWrt的ssr-puls插件中导出. 需要注意的是,gfw需要自己清理掉不属于域名的内容和去重. 再去分割网站分割. 
china_ip文件位置: /etc/ssrplus/china_ssr.txt
gfw文件位置: /etc/ssrplus/gfw_list.conf
